default_language_version:
  python: python3.10.12

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: python
        additional_dependencies:
          - isort==6.0.1
        pass_filenames: false
        always_run: true

      - id: black
        name: black
        entry: black .
        language: python
        additional_dependencies:
          - black==25.9.0
        pass_filenames: false
        always_run: true
