name = "ku-iqis-poster-presentation"
version = "1.0.0"
description = "The data analysis and poster presentation for the electro and physics experiments at DTU."
authors = [
  { name = "Kieran O'Neill", email = "zcd890@alumni.ku.dk" },
  { name = "Yao Su", email = "yaosu@nbi.ku.dk " }
]
readme = "README.md"
requires-python = ">=3.10.12"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
known_first_party = ["kuiqis"]
profile = "black"

[tool.pylint."messages control"]
disable = "all"
enable = [
  "empty-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]
ignore = ["setup.py", "__init__.py"]
